name: Publish

on:
  release:
    types:
      - published

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-npm:
    name: Publish fair-tools
    runs-on: ubuntu-24.04
    permissions:
      contents: read # To read the repository
      id-token: write # OIDC token for trusted publishing
    environment:
      name: npm
      url: https://www.npmjs.com/package/fair-tools
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Upgrade npm for OIDC support
        run: npm install -g npm@latest

      - run: npm ci
      - run: npm test
      - run: npm publish --access public

  github:
    name: GitHub Milestones
    permissions:
      issues: write # Required for write access to milestones
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-milestones.yml@2.2.0
    with:
      version: ${{ github.event.release.tag_name }}
