name: Reusable Tests

on:
  workflow_call:
    inputs:
      node-version:
        description: Node.js version to test
        type: number
        required: true

permissions: {}

jobs:
  test:
    name: Node.js ${{ inputs.node-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone the repo.

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
