name: Tests

on:
  push:
    branches:
      - trunk
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.label }}
    strategy:
      matrix:
        node-version:
          - 18 # Lowest supported
          - 20
          - 22
          - 24 # Latest LTS
        label:
          - Test
      fail-fast: false
    permissions:
      contents: read # Needed to clone the repo.
    uses: ./.github/workflows/reusable-tests.yml
    with:
      node-version: ${{ matrix.node-version }}
